abbr -a -U -- dc docker-compose
abbr -a -U -- dvorak 'setxkbmap -model pc104 -layout us,ru -variant dvorak, -option grp:alt_shift_toggle'
abbr -a -U -- execlip 'fish -c (xclip -o)'
abbr -a -U -- gB "git switch (git branch --all | string replace 'remotes/origin/' '' | string trim | fzf)"
abbr -a -U -- gb 'git switch (git branch | string trim | fzf)'
abbr -a -U -- gBFG "git for-each-ref --format '%(refname:short)' refs/heads | grep -v master | xargs git branch -D"
abbr -a -U -- ga 'git add'
abbr -a -U -- gamend 'git commit --amend --no-edit'
abbr -a -U -- gcb 'git switch -c'
abbr -a -U -- gcd 'cd (git rev-parse --show-toplevel)'
abbr -a -U -- gclean 'git clean -fd'
abbr -a -U -- gcom 'git commit'
abbr -a -U -- gd 'git diff'
abbr -a -U -- gdca 'git diff --cached'
abbr -a -U -- gfa 'git fetch --all --prune --tags'
abbr -a -U -- ghash 'git rev-parse --short HEAD'
abbr -a -U -- ginit 'git init ;and git commit -m "root" --allow-empty'
abbr -a -U -- gl 'git pull'
abbr -a -U -- gp 'git push'
abbr -a -U -- gpf 'git push --force-with-lease'
abbr -a -U -- gpu "git push -u origin (git branch | grep \* | awk '{print \$2}')"
abbr -a -U -- grba 'git rebase --abort'
abbr -a -U -- grbc 'git rebase --continue'
abbr -a -U -- grbs 'git rebase --skip'
abbr -a -U -- gsm 'git switch master'
abbr -a -U -- gst 'git status --short --branch'
abbr -a -U -- gsw 'git switch'
abbr -a -U -- nocaps 'setxkbmap -option ctrl:nocaps'
abbr -a -U -- suspend systemctl\ suspend
abbr -a -U -- v 'nvim +term'
abbr -a -U -- weather 'curl wttr.in/guangzhou'
