abbr -a -U -- ava-inspect 'node --inspect=localhost:44444 ./node_modules/ava/profile.js'
abbr -a -U -- dc docker-compose
abbr -a -U -- dvorak 'setxkbmap -model pc104 -layout us,ru -variant dvorak, -option grp:alt_shift_toggle'
abbr -a -U -- ecs examus-create-session
abbr -a -U -- ga 'git add'
abbr -a -U -- gamend 'git commit --amend --no-edit'
abbr -a -U -- gb 'git branch'
abbr -a -U -- gcb 'git checkout -b'
abbr -a -U -- gcd 'cd (git rev-parse --show-toplevel)'
abbr -a -U -- gclean 'git clean -fd'
abbr -a -U -- gcm 'git checkout master'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gcom 'git commit'
abbr -a -U -- gcp 'git cherry-pick'
abbr -a -U -- gd 'git diff'
abbr -a -U -- gdca 'git diff --cached'
abbr -a -U -- gfa 'git fetch --all --prune --tags'
abbr -a -U -- ghash 'git rev-parse --short HEAD'
abbr -a -U -- ginit 'git init ;and git commit -m "root" --allow-empty'
abbr -a -U -- gl 'git pull'
abbr -a -U -- gp 'git push'
abbr -a -U -- gpf 'git push --force-with-lease'
abbr -a -U -- gpu 'git push -u origin'
abbr -a -U -- gr 'git reset'
abbr -a -U -- grb 'git rebase'
abbr -a -U -- grba 'git rebase --abort'
abbr -a -U -- grbc 'git rebase --continue'
abbr -a -U -- grbs 'git rebase --skip'
abbr -a -U -- grh 'git reset HEAD'
abbr -a -U -- grhh 'git reset --hard HEAD'
abbr -a -U -- gst 'git status --short --branch'
abbr -a -U -- s sudo
abbr -a -U -- -nrepl clj\ -Sdeps\ \'\{:deps\ \{nrepl/nrepl\ \{:mvn/version\ \"0.5.3\"\}\}\}\'\ -m\ nrepl.cmdline
abbr -a -U -- suspend systemctl\ suspend
