#!/bin/bash

##
# This script installs vim-plug for neovim and then runs :PlugInstall.
# The homepage of `vim-plug` is https://github.com/junegunn/vim-plug.
##

curl -#fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

nvim +':PlugInstall'
