#!/bin/bash

### Install the latest nodejs on a brand-new Ubuntu.
### @see https://docs.npmjs.com/getting-started/fixing-npm-permissions

echo
echo Install npm, and n, and the latest node.
sudo apt-get install npm -y >/dev/null \
  && sudo npm i -g n \
  && sudo n latest

echo
echo Install yarn.

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg \
  | sudo apt-key add -

echo "deb https://dl.yarnpkg.com/debian/ stable main" \
  | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt-get update >/dev/null
sudo apt-get install yarn -y >/dev/null


### Workaround to install npm packages from private repos.

echo "\
Host github.com
  User git

Host gitlab.com
  User git
" >> ~/.ssh/config
