#!/bin/sh

cd $(dirname $0)

RESULT=result/activate

home-manager build --flake .

if test ! -e $RESULT; then
  echo >&2 ERROR: failed to build home configuration
  exit 1
fi


nix profile remove 0 1 2 3 4 5 6 7 8 9 10
$RESULT
