#!/bin/sh

RESULT=result/activate

home-manager build --flake .

# 
sudo chmod a+w $RESULT
nvim $RESULT +':%s/nix-env -i /nix profile install /' +wq!
sudo chmod a-w $RESULT

nix profile remove home-manager
$RESULT

sudo rm $RESULT
