#!/bin/sh

cd $(dirname $0)

RESULT=result/activate

home-manager build --flake .

if test ! -e $RESULT; then
  echo >&2 ERROR: failed to build home configuration
  exit 1
fi

# 
sudo chmod a+w $RESULT
nvim $RESULT +':%s/nix-env -i /nix profile install /' +wq!
sudo chmod a-w $RESULT

nix profile remove home-manager
$RESULT

sudo rm $RESULT
